### ISSUE TITLE
Error compiling latest master branch

### ISSUE THREAD

**Issue by Reforge-Mark** [AshamaneProject/AshamaneCore#169]
**Legion branch compiles fine, but this latest BFA on master branch has one error so far and thus can not be compiled. OS Debian, linux**

`In file included from /root/AshamaneCore/src/common/Logging/Log.cpp:29:
In file included from /root/AshamaneCore/src/common/Asio/Strand.h:21:
/root/AshamaneCore/src/common/Asio/IoContext.h:50:36: error: no member named
      'restart' in 'boost::asio::io_service'
            void restart() { _impl.restart(); }
                             ~~~~~ ^
`

**Current behaviour:**

error on 9%

**Expected behaviour:**

Compile completely

**Project(s): <-- Mandatory**

- [ ] Issue found in a compiled master repo from Git.

**Operating system:** Debian

**Comment by 4fungroup** [comment]
You should use boost 1.67

**Comment by ReyDonovan** [comment]
@Reforge-Mark 
![Новый точечный рисунок](https://user-images.githubusercontent.com/25749510/64037234-c9d3aa80-cb5d-11e9-9f68-735fb6f8505f.jpg)


debian 9+ last update not error not warning Boost 1.62.0.1
------------------------------------------------
now test debian 10 build okey
------------------------------------------------

**Comment by Traesh** [comment]
Minimum Boost requirement version for Ashamane is 1.67 indeed

**Comment by ReyDonovan** [comment]
`Minimum Boost requirement version for Ashamane is 1.67 indeed`


@Traesh version doesn't matter

**Comment by DJBoxer** [comment]
> Minimum Boost requirement version for Ashamane is 1.67 indeed
> @Traesh version doesn't matter
@reydonovan

Version does make a difference, after reading your response in prior reply. I tried to build with 1.62 then 1.65.1 then I went and compiled 1.67 and it finally compiled and built source.

I am using ubuntu bionic beaver, maybe this only effects Debian 9 beening able to use 1.62?
